services:
  attack_server:
    container_name: attack_server
    build:
      context: attack_cli
      dockerfile: Dockerfile
    networks:
      outer_net:
        ipv4_address: 192.168.1.3
    ports:
      - 8080:8080
    command: tail -f /dev/null


  fast_api_server:
    build:
      context: fast_api_server
      dockerfile: Dockerfile
    container_name: fast_api_server
    networks:
      inner_net:
        ipv4_address: 10.10.0.2
    ports:
      - 8000:8000
    restart: always

  reverse_proxy_sever:
    build:
      context: reverse_proxy_server
      dockerfile: Dockerfile
    container_name: reverse_proxy_server
    networks:
      inner_net:
        ipv4_address: 10.10.0.3
      outer_net:
        ipv4_address: 192.168.1.2
    ports:
      - 9000:9000
    restart: always

networks:
  inner_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
  outer_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
